name: firebase_notification_center_repository
description: "A new Flutter package project."
version: 5.1.0
homepage:
publish_to: 'none'

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.4.2
  firebase_core: ^3.5.0

  notification_center_repository_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_notification_center.git
      path: packages/notification_center_repository_interface
      ref: 5.1.0

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
