name: flutter_notification_center
description: "A Flutter package for displaying notifications in a notification center."
publish_to: 'none' 

version: 1.4.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any

  flutter_animated_widgets:
    git:
      url: https://github.com/Iconica-Development/flutter_animated_widgets
      ref: 0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
