name: notification_center_repository_interface
description: "A new Flutter package project."
version: 5.1.0
repository: https://github.com/Iconica-Development/flutter_notification_center

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0

dev_dependencies:
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0
