name: flutter_notification_center_firebase
description: "A new Flutter project."
publish_to: "none"
version: 3.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

  # Firebase
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0

  cupertino_icons: ^1.0.2

  flutter_notification_center:
    git:
      url: https://github.com/Iconica-Development/flutter_notification_center
      ref: 3.0.1
      path: packages/flutter_notification_center

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
  uses-material-design: true
